### ISSUE TITLE
Device ID is longer than 12 chars!

### ISSUE THREAD

**Issue by diazsasak** [freshworkstudio/gps-tracking-nodejs#10]
I successfully save gps coordinate to database with TK110 (2 wire) using this project without any code modification. then when i bought TK110 4 wire cable (to cut off power). there are 2 version of TK110, 2 wire and 4 wire. the SMS command is different. and when i try to send data to server i got error : 

`/home/diaz/rent_car_tracker/gps_tracker_receiver/gps-tracking/lib/adapters/tk103.js:24
                if(cmd_start > 13)throw "Device ID is longer than 12 chars!";
                                  ^
Device ID is longer than 12 chars!
`
Do you have code for TK110 4 wire cable ? or how can i show the incoming message so i can substr() it by myself ? 

thank you

**Comment by gonzunigad** [comment]
Is TK110 using the same protocol as TK103? If it has a device ID longer than 12 characters, i could create a new adapter and upload it to the repo. Do you have the GPS Protocol PDF?
