### ISSUE TITLE
undefined request

### ISSUE THREAD

**Issue by gyurobenjamin** [freshworkstudio/gps-tracking-nodejs#13]
The only event what I got is the connected, and the first parameter is undefined.

```javascript
device.on("connected",function(data){
        console.log("I'm a new device connected");
        console.log(data); // this will be undefined
});
```

**Comment by gonzunigad** [comment]
Oh, you're right, this is probably a bug. I will look at it. What do you expect data to be? The original message of the device trying to connect?
