### ISSUE TITLE
Q50 device 

### ISSUE THREAD

**Issue by larytet** [freshworkstudio/gps-tracking-nodejs#17]
Hi,

Have you seen a GSM tracker which sends a ping packet (?) looking like this 

`[3G*1452592884*0009*LK,0,0,97]` 
followed by 
`[3G*1452592884*00CD*UD2,130418,133752,A,32.180347,N,34.8551140,E,2.78,278.5,0.0,6,100,95,0,0,00000000,7,255,425,2,33576,11402,161,33576,12403,139,33576,11401,138,33552,11301,135,33576,16283,131,33576,13862,129,33576,11881,129]`
The number 1452592884 is the device IEMI. Numbers `A,32.180347,N,34.8551140` mean N32.180347,E34.8551140

Thanks

**Comment by gonzunigad** [comment]
Hi! You can create ad adapter for this protocol. I will appreciate if you can add a PR with that new adapter if tou can.

**Comment by larytet** [comment]
This thing is UDP and requires a UDP server somewhere
