### ISSUE TITLE
I want to use for TK06A

### ISSUE THREAD

**Issue by surendrakumar1992** [freshworkstudio/gps-tracking-nodejs#2]
Hello folks,
I want to  use this for "TK06A" protocol. Please help me, how i can achieve this?

**Comment by gonzunigad** [comment]
Hey,

You can create custom adapters. You can checkout the tk103 adapter to know
how we do it.

Btw, you can send me the protocol documentarion of tk06a and we can give
you a base code so you can continue by your own.

It would be great if you can send us the working code to add it to the base
package.

**Comment by gonzunigad** [comment]
Or even if you bought me a TK06A device, i'll do my best to create the adapter and update the repo ;)
