### ISSUE TITLE
To Send Command to Device using Https

### ISSUE THREAD

**Issue by jAddict7** [freshworkstudio/gps-tracking-nodejs#27]
I am new to NodeJS, In the documentation an available option to send command is available,
`'cmd':'other_command'`

`this.send_comand = function(cmd,data){
var msg = [this.device.uid,cmd,data];
this.device.send(this.format_data(msg));
}`

But how to trigger this from http request to a specific connected device? Please do help. Thanks in advance.

**Comment by jAddict7** [comment]
```
var http = require('http');
http.createServer(function(req, res){
	server.send_to('device_id', 'command');
	res.end();
}).listen(3000);
```

**Comment by jona556** [comment]
how you set var server? for "server".send_to('device_id', 'command')

**Comment by jAddict7** [comment]
`var server` is already created when we use the library
