### ISSUE TITLE
Socket IO

### ISSUE THREAD

**Issue by rustywebguy** [freshworkstudio/gps-tracking-nodejs#3]
Is it possible for this to integrate with Socket IO?

**Comment by gonzunigad** [comment]
Yes, of course.
Just use it normally. Maybe inwill upload some demontest app with socket.io
and google maps.

**Comment by rustywebguy** [comment]
I tried to send to the socket data and creating a net.socket client with socket.io but I cannot get the data that I send to the socket.

**Comment by gonzunigad** [comment]
@rustywebguy i created a very basic demo app that uses socket.io to add a marker in a Google Map as soon as a packet is received by the server. 
https://github.com/freshworkstudio/gps-google-maps-socket-io

Tell me if you get it.

**Comment by gonzunigad** [comment]
You can test the app sending dummy data trough the emulator: 
http://gps-tracking-emulator.meteor.com/

![captura de pantalla 2015-06-23 a las 1 43 51](https://cloud.githubusercontent.com/assets/1103494/8299177/16b6985e-194b-11e5-8104-801faac4cbd2.png)
![captura de pantalla 2015-06-23 a las 1 54 57](https://cloud.githubusercontent.com/assets/1103494/8299178/16d459de-194b-11e5-9562-4ae450db5cef.png)
