### ISSUE TITLE
Problem with SPDX.

### ISSUE THREAD

**Issue by claytonmarinho** [freshworkstudio/gps-tracking-nodejs#5]
<code>gps-tracking@1.0.7 license should be a valid SPDX license expression</code> returns when installing gps-tracking.

I changed <code> "license": "GPLv3"</code> to <code>"license": "GPL-3.0"</code> and now give <code>npm WARN install Refusing to install gps-tracking as a dependency of itself</code>

Any ideia how solve this?

**Comment by gonzunigad** [comment]
Now it's fixed on #90e4c7c

**Comment by claytonmarinho** [comment]
Thanks.
