### ISSUE TITLE
i have a question about the command transmission

### ISSUE THREAD

**Issue by sherome** [freshworkstudio/gps-tracking-nodejs#6]
now I had problems transmission commands to gps device
Can you help me ? Gps device does not return data

[MEITRACK_GPRS_Protocol](http://www.meitrack.com/meitrack-support/protocol/MEITRACK_GPRS_Protocol.pdf)

> Example  

GPRS Sending @@O48,353358017784062,D00,0215080432_C2E03.jpg,0*DB\r\n
GPRS Reply The example cannot be displayed because of hexadecimal characters.

Do you have example code ?
I wrote a program by node JS
Please help.

**Comment by slachtar** [comment]
server doesn't support Meitrack protocols yet.
Have you integrated it?

**Comment by gonzunigad** [comment]
Sorry bout the dealy in my answer. Actually, Meitrack it's not implemented. It would be great if you can create an adapter (the documentation is on README.md) so anyone in the future can use it ;)

**Comment by gonzunigad** [comment]
Do you guys have a device to make some testing on this? i would like to implement meitrack.
