### ISSUE TITLE
Bug overflow

### ISSUE THREAD

**Issue by ioanb7** [freshworkstudio/gps-tracking-nodejs#8]
Hi, great library. It eased my work by a lot.

https://github.com/freshworkstudio/gps-tracking-nodejs/blob/master/lib/main.js#L195

This line should really try to parse the data multiple times, as the clients can send messages too quickly and TCP can put them in a single packet. Thus, the adapter cannot return two objects with values.

Do you mind if I modify this and push a pull request?

Also, I've made an adapter "simplicity" that gets JSON messages from a custom android app and sends it to another tcp server. It is meant to be an alternative to the tracking system that the fire engines have in northern UK. Let me know if you want me to open source it and add some documentations. I can bother with it if you will link it up.

Regards,
Ioan.

**Comment by gonzunigad** [comment]
Hi!

It would be great if you can help me to improve the library.

What do you need for my part?

Regards!

**Comment by hamid-brahim** [comment]
Hiii
Great job. I have installed it but when de device tries to connect to de server i'm getting this message= " # is trying 'other" but is not loged. Action not executed" coud you please what shoukd I do?
thanks

**Comment by gonzunigad** [comment]
Was you using a TK103 device? Maybe thats the problem. Send me the Protocol of the device you are using so i can check whats happening.
